version: '3.8'
services:

  oracle:
    image: loliconneko/oracle-ee-11g
    container_name: oracle
    ports:
      - 1521:1521
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1521/ORCLCDB as sysdba", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5

  spring:
    container_name: springboot
    build:
      context: ./backend
    ports:
      - "8181:8181"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle:1521/EE.oracle.docker
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=oracle
    depends_on:
      - oracle


  react:
    container_name: reactjs
    build:
      context: ./frontend
    ports:
      - "3000:3000"

volumes:
  oracle-data:
    driver: local
